- name: Install Apache and PHP
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - php
   - php-mysql

- name: Start and Enable Apache Server to start on boot
  service: name=httpd state=started enabled=yes

- name: Enable the firewall port for Apache
  firewalld: port=80/tcp permanent=true state=enabled immediate=yes
    
