---
- name: Install git and firewalld  
  hosts: all
  become: true
  roles: 
    - common

- name: Install and configure MariaDB
  hosts: db
  become: true
  roles:
    - mariadb

- name: Install Apache, PHP and configure website code
  hosts: web
  become: true
  roles:
    - web-server

- name: Deploy app
  hosts: web
  become: true
  roles:
    - deploy
